version: '3.9'

services:
    db:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: heart_container
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
